# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170404_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nag_allowed',
            field=models.CharField(choices=[('1', '10 minutes'), ('2', '30 minutes'), ('3', '1 Hour')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(choices=[('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly')], default=1, max_length=1),
        ),
    ]
