# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170409_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nag_allowed',
        ),
    ]
