# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_nag_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
